<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>acd9f3d0-6b08-4dec-841f-0e049f242e32</UserSecretsId>
		<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
	</PropertyGroup>

	<ItemGroup>
		<!-- <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.22.1" /> -->
		<PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
		<PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="7.0.10" />
		<PackageReference Include="Scrutor" Version="4.2.2" />
		<PackageReference Include="CorrelationId" Version="3.0.1" />

		<PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning" Version="5.1.0" />
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="7.0.12" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="7.0.12">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\InternetShop.Contract\InternetShop.Contract.csproj" />
	  <ProjectReference Include="..\InternetShop.Data\InternetShop.Data.csproj" />
	  <ProjectReference Include="..\InternetShop.Service\InternetShop.Service.csproj" />
	</ItemGroup>

</Project>
